### ISSUE TITLE
Make Blog Summary Image NOT Show at Top of Entry

### ISSUE THREAD

**Issue by CBPSC** [DNNCommunity/DNNCommunityTheme#63]
## Is your feature request related to a problem?
**Please describe.**
Currently the DNN blog module does not provide an option to NOT include the summary image in the blog entry itself. So the summary image is placed at the top of the entry which jacks up the formatting majorly and in some cases repeats the image twice.

## Describe the solution you'd like
I would either like the summary image to NOT be included by default or for the blog module to offer the option to the author to include or not include ( a checkbox would do) the summary image in the blog entry.

## Describe alternatives you've considered
off by default or provide the user with the option to explicitly state what they want

## Additional context
https://dnncommunity.org/blogs/Post/1109/2019-DNN-MVP-Nominations-are-Open

**Comment by Tychodewaard** [comment]
Is this issue related to the skin or should it be on the DNN Blog repo?

**Comment by valadas** [comment]
Hmm, not sure, is the blog template for the site handled in the theme or as website content @david-poindexter

**Comment by david-poindexter** [comment]
@CBPSC @Tychodewaard and @valadas - the template for the blog on the community site is indeed managed within the theme package.  In order to make a change like this in the template, I think we need a proposed design before proceeding.  I personally do not think removing the blog image from the blog detail view is the ideal solution.

Regarding the feature to give the author the option to include or not include the image on the detail view, that should be addressed in the Blog module repo.

**Comment by valadas** [comment]
On the link provided is the image the main image + the image is included in the html of the blog entry? Because not all posts have that duplication. If you ask me, I think that main image should always show, but if there is a desire to have it configurable, then yes, that would be in the blog repo.
